import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Layout/Header";
import { ProductProvider } from "@/components/Layout/ProductContext";

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

export const metadata = {
	title: "MyStore",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<ProductProvider>
				<body
					className={`${geistSans.variable} ${geistMono.variable} antialiased`}
				>

					{children}

				</body>
			</ProductProvider>
		</html>
	);
}
